const data = {
  products: [
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "./images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 1.5,
      numReviews: 5,
      description: 'high quality shirt',
    },
    {
        name: "Nike Slim shirt",
        slug: "nike-slim-shirt",
        category: "Shirts",
        image: "./images/p2.jpg",
        price: 120,
        countInStock: 0,
        brand: 'Nike',
        rating: 2.5,
        numReviews: 8,
        description: 'high quality shirt',
      },
      {
        name: "Nike Slim shirt",
        slug: "nike-slim-shirt",
        category: "Shirts",
        image: "./images/p3.jpg",
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 3.5,
        numReviews: 9,
        description: 'high quality shirt',
      },
      {
        name: "Nike Slim shirt",
        slug: "nike-slim-shirt",
        category: "Shirts",
        image: "./images/p4.jpg",
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
  ],
};

export default data;